#!/usr/bin/env node
// 将面板的静态前端资源（共享 CSS + dashboard 客户端 JS）从 worker bundle 中抽出，
// 写为带内容哈希的独立文件交给 Cloudflare 静态资源托管，浏览器可长期缓存、不再随
// worker 重复下发，worker 体积同步缩小。
//
// 源文件（issue #20：真实 .css/.js 源文件，取代旧的模板字面量 chunk 文件）：
//   src/ui/dashboard/client/app.css
//   src/ui/dashboard/client/app.js  ← 含 __CURRENT_VERSION__ / __GITHUB_RAW_URL__
//                                      占位符，构建时替换为 src/util/version.js 的值
//
// 产物（均经 esbuild transform 压缩后再哈希，哈希对应实际下发的字节）：
//   public/static/app.<hash>.css   ← app.css 压缩后哈希
//   public/static/app.<hash>.js    ← app.js 占位符替换 + 压缩后哈希
//   src/ui/asset-manifest.js       ← 上述带哈希路径，供 dashboard.js / login.js 引用
//
// 必须在 esbuild 打包前运行：dashboard.js / login.js 改为引用 manifest，
// 从而把 CSS / 客户端 JS 大字符串移出 worker 依赖图。

import { readdirSync, mkdirSync, readFileSync, writeFileSync, rmSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import { transform } from 'esbuild';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..');
const staticDir = resolve(repoRoot, 'public/static');
const manifestPath = resolve(repoRoot, 'src/ui/asset-manifest.js');
const clientDir = resolve(repoRoot, 'src/ui/dashboard/client');

const CSS_COMMON = readFileSync(resolve(clientDir, 'app.css'), 'utf8');
const { CURRENT_VERSION, GITHUB_RAW_URL } = await import('../src/util/version.js');

// 客户端源文件里的版本号/更新地址是占位符（保持单一数据源 src/util/version.js），
// 构建时替换为真实值后再哈希，与旧实现（模块导入时插值）行为一致。
const APP_JS = readFileSync(resolve(clientDir, 'app.js'), 'utf8')
    .replaceAll('__CURRENT_VERSION__', CURRENT_VERSION)
    .replaceAll('__GITHUB_RAW_URL__', GITHUB_RAW_URL);
if (APP_JS.includes('__CURRENT_VERSION__') || APP_JS.includes('__GITHUB_RAW_URL__')) {
    throw new Error('build-assets: unresolved version placeholder left in app.js output');
}

// 客户端资源以前原样下发（渲染阻塞的 214 KB CSS / 222 KB JS）——npm run build 的
// --minify 只作用于 worker bundle。用 esbuild transform（不是 bundle）压缩：transform
// 保留顶层作用域，HTML 里的内联 onclick= 仍能找到 app.js 的全局函数声明。
const minified = async (source, loader) =>
    (await transform(source, { loader, minify: true, target: 'es2022' })).code;

const CSS_OUT = await minified(CSS_COMMON, 'css');
const JS_OUT = await minified(APP_JS, 'js');
// 压缩若改写了顶层函数名，内联 onclick= 会静默失效——直接构建失败比上线后才发现好。
if (!/function purgeCache\b/.test(JS_OUT)) {
    throw new Error('build-assets: minifier renamed top-level function declarations; inline onclick= handlers would break');
}

const hash = (s) => createHash('sha256').update(s).digest('hex').slice(0, 10);
const cssName = `app.${hash(CSS_OUT)}.css`;
const jsName = `app.${hash(JS_OUT)}.js`;

// 清掉旧哈希产物，避免堆积。
if (existsSync(staticDir)) {
    for (const f of readdirSync(staticDir)) {
        if (/^app\.[0-9a-f]+\.(css|js)$/.test(f)) rmSync(resolve(staticDir, f));
    }
}
mkdirSync(staticDir, { recursive: true });

writeFileSync(resolve(staticDir, cssName), CSS_OUT);
writeFileSync(resolve(staticDir, jsName), JS_OUT);

const manifest = `// AUTO-GENERATED by scripts/build-assets.mjs — do not edit. Run 'npm run build'.
// 面板静态资源的带哈希路径；内容变化时哈希变化，自动失效浏览器缓存。
export const CSS_HREF = "/static/${cssName}";
export const APP_JS_SRC = "/static/${jsName}";
`;
writeFileSync(manifestPath, manifest);

const kib = (s) => (s.length / 1024).toFixed(1);
console.log(`build-assets: ${cssName} (${kib(CSS_COMMON)} → ${kib(CSS_OUT)} KiB), ${jsName} (${kib(APP_JS)} → ${kib(JS_OUT)} KiB)`);
