#!/usr/bin/env node
// Builds the console's browser assets into content-hashed files that Cloudflare static assets serve:
//   src/ui/console/main.js     → public/static/console.<hash>.js   (esbuild bundle, IIFE, minified)
//   src/ui/console/console.css → public/static/console.<hash>.css  (minified)
//   src/ui/asset-manifest.js   ← the hashed paths, imported by dashboard.js and login.js
// Run before the worker bundle, since the worker imports the manifest.

import { readdirSync, mkdirSync, readFileSync, writeFileSync, rmSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import { build } from 'esbuild';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..');
const staticDir = resolve(repoRoot, 'public/static');
const consoleDir = resolve(repoRoot, 'src/ui/console');
const { CURRENT_VERSION, GITHUB_RAW_URL } = await import('../src/util/version.js');

const bundle = async (entry, extra = {}) => {
    const out = await build({
        entryPoints: [resolve(consoleDir, entry)],
        bundle: true,
        minify: true,
        write: false,
        target: 'es2022',
        logLevel: 'warning',
        ...extra,
    });
    return out.outputFiles[0].text;
};

const JS_OUT = await bundle('main.js', {
    format: 'iife',
    define: {
        __CURRENT_VERSION__: JSON.stringify(CURRENT_VERSION),
        __GITHUB_RAW_URL__: JSON.stringify(GITHUB_RAW_URL),
    },
});
const CSS_OUT = await bundle('console.css');

const hash = s => createHash('sha256').update(s).digest('hex').slice(0, 10);
const jsName = `console.${hash(JS_OUT)}.js`;
const cssName = `console.${hash(CSS_OUT)}.css`;

// Write only on change: `wrangler dev` watches src/, so rewriting an unchanged manifest would
// trigger its custom build again in an endless loop.
const manifestPath = resolve(repoRoot, 'src/ui/asset-manifest.js');
const manifest = `// AUTO-GENERATED by scripts/build-assets.mjs. Do not edit. Run 'npm run build'.
export const CSS_HREF = "/static/${cssName}";
export const APP_JS_SRC = "/static/${jsName}";
`;
mkdirSync(staticDir, { recursive: true });
for (const f of readdirSync(staticDir)) {
    if (/^(app|console)\.[0-9a-f]+\.(css|js)$/.test(f) && f !== jsName && f !== cssName) rmSync(resolve(staticDir, f));
}
if (!existsSync(resolve(staticDir, jsName))) writeFileSync(resolve(staticDir, jsName), JS_OUT);
if (!existsSync(resolve(staticDir, cssName))) writeFileSync(resolve(staticDir, cssName), CSS_OUT);
if (!existsSync(manifestPath) || readFileSync(manifestPath, 'utf8') !== manifest) writeFileSync(manifestPath, manifest);

console.log(`build-assets: ${jsName} (${JS_OUT.length} B), ${cssName} (${CSS_OUT.length} B)`);
