#!/usr/bin/env node
// 将面板的静态前端资源（共享 CSS + dashboard 客户端 JS）从 worker bundle 中抽出，
// 写为带内容哈希的独立文件交给 Cloudflare 静态资源托管，浏览器可长期缓存、不再随
// worker 重复下发，worker 体积同步缩小。
//
// 源文件（issue #20：真实 .css/.js 源文件，取代旧的模板字面量 chunk 文件）：
//   src/ui/dashboard/client/app.css
//   src/ui/dashboard/client/app.js  ← 含 __CURRENT_VERSION__ / __GITHUB_RAW_URL__
//                                      占位符，构建时替换为 src/util/version.js 的值
//
// 产物：
//   public/static/app.<hash>.css   ← app.css 原样哈希
//   public/static/app.<hash>.js    ← app.js 占位符替换后哈希
//   src/ui/asset-manifest.js       ← 上述带哈希路径，供 dashboard.js / login.js 引用
//
// 必须在 esbuild 打包前运行：dashboard.js / login.js 改为引用 manifest，
// 从而把 CSS / 客户端 JS 大字符串移出 worker 依赖图。

import { readdirSync, mkdirSync, readFileSync, writeFileSync, rmSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..');
const staticDir = resolve(repoRoot, 'public/static');
const manifestPath = resolve(repoRoot, 'src/ui/asset-manifest.js');
const clientDir = resolve(repoRoot, 'src/ui/dashboard/client');

const CSS_COMMON = readFileSync(resolve(clientDir, 'app.css'), 'utf8');
const { CURRENT_VERSION, GITHUB_RAW_URL } = await import('../src/util/version.js');

// 客户端源文件里的版本号/更新地址是占位符（保持单一数据源 src/util/version.js），
// 构建时替换为真实值后再哈希，与旧实现（模块导入时插值）行为一致。
const APP_JS = readFileSync(resolve(clientDir, 'app.js'), 'utf8')
    .replaceAll('__CURRENT_VERSION__', CURRENT_VERSION)
    .replaceAll('__GITHUB_RAW_URL__', GITHUB_RAW_URL);
if (APP_JS.includes('__CURRENT_VERSION__') || APP_JS.includes('__GITHUB_RAW_URL__')) {
    throw new Error('build-assets: unresolved version placeholder left in app.js output');
}

const hash = (s) => createHash('sha256').update(s).digest('hex').slice(0, 10);
const cssName = `app.${hash(CSS_COMMON)}.css`;
const jsName = `app.${hash(APP_JS)}.js`;

// 清掉旧哈希产物，避免堆积。
if (existsSync(staticDir)) {
    for (const f of readdirSync(staticDir)) {
        if (/^app\.[0-9a-f]+\.(css|js)$/.test(f)) rmSync(resolve(staticDir, f));
    }
}
mkdirSync(staticDir, { recursive: true });

writeFileSync(resolve(staticDir, cssName), CSS_COMMON);
writeFileSync(resolve(staticDir, jsName), APP_JS);

const manifest = `// AUTO-GENERATED by scripts/build-assets.mjs — do not edit. Run 'npm run build'.
// 面板静态资源的带哈希路径；内容变化时哈希变化，自动失效浏览器缓存。
export const CSS_HREF = "/static/${cssName}";
export const APP_JS_SRC = "/static/${jsName}";
`;
writeFileSync(manifestPath, manifest);

console.log(`build-assets: ${cssName} (${(CSS_COMMON.length / 1024).toFixed(1)} KiB), ${jsName} (${(APP_JS.length / 1024).toFixed(1)} KiB)`);
